### ISSUE TITLE
ontbrekende keuzeopties batch editing

### ISSUE THREAD

**Issue by roxannewyns** [libis/ca_cag#2]
assigned @aruijmen 

Bij batch editing ontbreken er bepaalde relatietypes as keuzeoptie.

Het veld bewaarplaats (ca_entities relatieveld) heeft normaal 3 relatietypes
is bewaarinsteling van
heeft als beheerder
heeft als eigenaar
maar bewaarinstelling staat niet in de keuzelijst. 

![capture1](https://cloud.githubusercontent.com/assets/3798589/8159569/4967f3f8-1368-11e5-9d13-91aa6745f69f.JPG)

Ik heb vanalles geprobeerd:
Bij beheren > relatietypes > object x entities het record 'bewaarinstelling' iets aangepast en gesaved om te herindexeren
Bij 'standaard object editor' de beperking van de relatietypes aangepast en gesaved. Zo heb ik ook eens het relatietype vervaardiger toegevoegd. Dit verscheen direct mee in de keuzelijst voor batch editing. 
In de keuzelijst van 'standaard object editor' alle relatietypes verwijderd en enkel relatietype bewaarinstelling laten staan. Dan was de lijst in batch editing gewoon leeg. 

![capture](https://cloud.githubusercontent.com/assets/3798589/8159595/80b05152-1368-11e5-811d-853ff59be676.JPG)

Hetzelfde probleem bestaat op het tabblad verwerving bi jbatch editing, waar ook het veld 'bewaarinstelling staat'

**Comment by aruijmen** [comment]
Solved !!
Oorzaak van het probleem: bij het relatietype 'is bewaarinstelling van' 
![image](https://cloud.githubusercontent.com/assets/3263690/8178978/6afe63ca-1413-11e5-9e4d-203ed4389af4.png)

waren restrictie op type voor linkerkant en voor rechterkant ingevuld.
Ik heb deze restricties op -NONE- gezet.
Het was ook de enige optie waarbij dit ingevuld was.
Hopelijk ontstaat hierdoor nu geen ander probleem (de keuze kan nu ook op andere plaatsen verschijnen)
Anita
