### ISSUE TITLE
adlibObjectNummer toevoegen aan sort

### ISSUE THREAD

**Issue by roxannewyns** [libis/ca_cag#4]
adlibObjectNummer toevoegen aan sorteer lijst. 

Ik vind niet direct terug hoe ik een veld aan de lijst kan toevoegen in de linkerhoek. Voor zover ik kan zien staan de settings in het metadata element correct aangevinkt. Misschien in een conf file? 
Kan jij eens kijken? Creative commons moet ook toegevoegd geweest zijn, maar kan me niet herinneren hoe.

![capture](https://cloud.githubusercontent.com/assets/3798589/9996898/a6e16db6-6089-11e5-8429-13c54a279288.JPG)

**Comment by roxannewyns** [comment]
Input Sam: Je kan een aantal dingen configureren bij metadata elementen. Maar in sommige van de gevallen ging dat niet en dan heb ik dit aangepast in de code. Waar herinner ik mij niet meer zeker, maar het was vermoed ik in de BaseFindController

**Comment by aruijmen** [comment]
Analyse:
Sorteren op adlib objectnummer was mogelijk in de lijst-weergave (door klikken op de kolomhoofding).
Bij het opbouwen van bovenstaand scherm wordt rekening gehouden met het object type_id.
Enkel metadata elementen die beperkt werden tot object type_id werden toegevoegd aan de standaard sort-lijst.  Vermits adlib objecnummer geen beperking op object type_id heeft, kan dit niet getoond worden.
Oplossing:
Het metadata element adlib objectnummer in systeembeheer/metadata elements 
ipv een type beperking objecten/-
![capture](https://cloud.githubusercontent.com/assets/3263690/15670537/59a44e7e-2726-11e6-86c6-754eec142dec.PNG)

zowel een type beperking geven objecten/Objecten 
![capture](https://cloud.githubusercontent.com/assets/3263690/15670572/7ee84d7a-2726-11e6-9c48-e51a01dc91cb.PNG)
als objecten/Algemene info
![capture](https://cloud.githubusercontent.com/assets/3263690/15670624/a8e31bf0-2726-11e6-97e1-c0479525f80c.PNG)
