### ISSUE TITLE
"Gerelateerd nummer" needs to be synced to Omeka

### ISSUE THREAD

**Issue by roxannewyns** [libis/ca_cag#5]
cc @aruijmen 

Naeem to discuss with Anita. Probably a creation of a display template is needed? 

"Gerelateerd nummer" has been added to the export display for objects. 
The data has to be synced to Omeka as following. Repeating values have to be put in a new field.

Test Gerelateerd nummer - instelling; Test Gerelateerd nummer; Test Type nummer
Test2 Gerelateerd nummer - instelling; Test2 Gerelateerd nummer; Test2 Type nummer

**Comment by roxannewyns** [comment]
in de prodcutie synchroniseerd dit veld niet. het zit nochtans in de mapping en 
SPLITTOONE,ca_objects.objectInventarisnrBpltsInfo,$,items::object:Gerelateerd nummer

net volgende collectiveaccess set gesynchroniseerd RW18022016 (1 item)
Update gelukt, maar het veld gerelateerd nummer is nog leeg.
Okema object: /items/edit/79828

**Comment by naeemmuhammad** [comment]
Template information was in a wrong display bundle. I have put it in the correct display bundle ( expHVL_objecten_lib) and integration for Gerelateerd nummer is working.

Roxanne is to test before we close this issue.

**Comment by roxannewyns** [comment]
test ok
